### ISSUE TITLE
tutorial material should be here, not code repo

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics-Tutorial#12]
The TASBE tutorial material currently in the gh-pages branch of the code repo should instead be here: the code repo website should only contain the actual website material, not the tutorial material is links to.

**Comment by coverney** [comment]
Is this issue still applicable since the website represents the entire TASBE codebase?

**Comment by jakebeal** [comment]
No, this has been resolved at this point.

**Comment by jakebeal** [comment]
Also, I just figured out why we were still having to go to https://tasbe.github.io/TASBE, rather than just https://tasbe.github.io/.  It's because I named the repository "TASBE" but was supposed to name it "TASBE.github.io" --- I have changed this, but you'll need to fix the remote pointer in your local copy of the repository.

**Comment by coverney** [comment]
Great! I updated the links. The changes should be reflected soon.
