### ISSUE TITLE
geostd var function call causes error on Octave 4.0.0

### ISSUE THREAD

**Issue by jegentile** [TASBE/TASBEFlowAnalytics-Tutorial#19]
Line 19 in geostd.m is uses var to compute the weighted variance
`s = 10.^sqrt(var(log10(data(valid)),weights(valid)));`
However, Octave's native `var` function cannot compute the weighted variance.

**Comment by jakebeal** [comment]
Fixed in [TASBEFlowAnalytics release 2.0](https://github.com/TASBE/TASBEFlowAnalytics/releases/tag/2.0.0)
