### ISSUE TITLE
'svnversion'

### ISSUE THREAD

**Issue by kkiwimagi** [TASBE/TASBEFlowAnalytics-Tutorial#3]
Hi Jake,

Slowly working through program. So far have not found many issues.
![capture](https://cloud.githubusercontent.com/assets/27301942/25408532/5ecfced2-29dc-11e7-8e5e-c903638c63e9.PNG)

It looks like the version is not storing in the CM but this really is a little bug. I'll keep looking for more:)

Best,
Katherine

**Comment by jakebeal** [comment]
Good catch --- thank you. The automatic version tracking broke when we switched to Git. I'm going to have to think about what's the right way to fix this.

**Comment by jakebeal** [comment]
Fixed by https://github.com/TASBE/TASBEFlowAnalytics/issues/117
