### ISSUE TITLE
Set up regression testing for tutorials

### ISSUE THREAD

**Issue by coverney** [TASBE/TASBEFlowAnalytics-Tutorial#31]
Implement regression testing in order to automatically check if the tutorials are always up to date. The test could involve running the ``exercise.m`` files for each tutorial and checking for any critical errors.

**Comment by jakebeal** [comment]
This can probably be bootstrapped by copying the regression testing setup from the main TASBE code package.

**Comment by coverney** [comment]
This issue is the same as #139 in TASBEFlowAnalytics.
