### ISSUE TITLE
Why set translation channel min?

### ISSUE THREAD

**Issue by kkiwimagi** [TASBE/TASBEFlowAnalytics-Tutorial#7]
CM=set_translation_channel_min(CM,[2,2,2]); % Ignore channel data for ith channel if below 10^[value(i)]

What is this doing? and Why do it?

Thank you for your help,
Katherine

**Comment by jakebeal** [comment]
With transient transfection, multi-color files generally have a linear component (giving the translation conversion factor), a non-transfected population, and a "curve" connecting between them. This value should be set to clip out everything below the linear component.

**Comment by kkiwimagi** [comment]
Awesome, thank you.
