### ISSUE TITLE
filterC, filterW

### ISSUE THREAD

**Issue by kkiwimagi** [TASBE/TASBEFlowAnalytics-Tutorial#8]
When are the laser, FilterCenter and FilterWidth used through out the TASBE protocol?
In other words,  why are they important when defining a channel?

Thank you again,
K

**Comment by jakebeal** [comment]
Different machines have different names for their channels, as well as different laser/filter combinations for the "same" channel.  Without somebody adding this metadata, it's impossible to know whether "PE-Texas-Red-A" in one file is the same as "PE-Tx-Rd-Yg-A" in another, or whether two "FL1-A" channels actually are measuring anything even vaguely related.

The code thus uses these for making sure it's got the right channel when it's looking at a set of data. The code probably does not do this validation in as many places as it ought to, unfortunately.
