### ISSUE TITLE
adding autofluorescence back in

### ISSUE THREAD

**Issue by kkiwimagi** [TASBE/TASBEFlowAnalytics-Tutorial#9]
AP=setUseAutoFluorescence(AP,false');% Add autofluorescence back in after removing for compensation?

When would you want to add autofluorescence back in?

**Comment by jakebeal** [comment]
It's unusual, but there have been cases where the particular experimental analysis that I was doing wanted to compare the fold difference of a value versus autofluorescence.  For that, you want to compensate and then add it back in.
